# Generated by Django 2.1.5 on 2019-01-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190124_2118'),
        ('users', '0003_auto_20190123_1028'),
    ]

    operations = [
    ]
