# Generated by Django 2.1.5 on 2019-01-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190127_2219'),
        ('users', '0005_merge_20190129_1321'),
    ]

    operations = [
    ]
