# Generated by Django 2.1.5 on 2019-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190127_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('Higher', 'Higher Education'), ('Basic', 'Basic Higher Education'), ('Secondary', 'Secondary Education'), ('Special', 'Secondary Special Education')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
