# Generated by Django 2.1.5 on 2019-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190129_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('', '--------------'), ('Higher', 'Higher Education'), ('Basic', 'Basic Higher Education'), ('Secondary', 'Secondary Education'), ('Special', 'Secondary Special Education')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', '--------------'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
