# Generated by Django 2.1.5 on 2019-01-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_category',
                 models.ForeignKey(blank=True, db_column='parent_id',
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='tutors.CategoryQuestion')),
            ],
            options={
                'db_table': 'Categories_questions',
            },
        ),
    ]
