# Generated by Django 2.1.5 on 2019-01-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tutors', '0002_categoryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_question',
            field=models.ForeignKey(blank=True, db_column='category_id',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='tutors.CategoryQuestion'),
        ),
    ]
