# Generated by Django 2.1.5 on 2019-01-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tutors', '0004_auto_20190122_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='answer_id',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='tutors.Question'),
        ),
    ]
