# Generated by Django 2.1.5 on 2019-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0009_auto_20190125_1532'),
        ('tutors', '0009_auto_20190125_1910'),
    ]

    operations = [
    ]
