# Generated by Django 2.1.5 on 2019-01-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.CategoryQuestion'),
        ),
    ]
