# Generated by Django 2.1.5 on 2019-02-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tutors', '0012_auto_20190129_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category_question',
            field=models.ForeignKey(blank=True, db_column='category_id',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='tutors.CategoryQuestion'),
        ),
    ]
