# Generated by Django 2.1.5 on 2019-01-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0012_auto_20190129_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('question', 'answer_text')},
        ),
    ]
