# Generated by Django 2.1.5 on 2019-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190130_2333'),
        ('tutors', '0013_auto_20190130_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('quiz', 'title')},
        ),
    ]
