dist: trusty

language: python
python:
  - "3.6"


addons:
  sonarcloud:
    organization: $ORGANIZATION
  token:
      secure: $SONAR_TOKEN


before_install:
  - git fetch --unshallow || true
  - export DJANGO_SETTINGS_MODULE=CultureAnalyzer.settings

install:
  - pip install -r requirements.txt
  - pip install -r build-requirements.txt

script:
  - ./build_script.sh
  - cat pylint_report_file.txt
  - sonar-scanner

notifications:
  email:
    recipients:
      - test.mail.client008@gmail.com
    on_success: always
    on_failure: always
