dist: trusty

language: python
python:
  - "3.6"


addons:
  sonarcloud:
    organization: $ORGANIZATION
  token:
      secure: $SONAR_TOKEN


before_install:
  - export DJANGO_SETTINGS_MODULE=CultureAnalyzer.settings.test_settings

install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pylint-django


script:
  - python manage.py test
  - sonar-scanner


notifications:
  email:
  - $DEFAULT_EMAIL
