version: '3.6'

services:
  db:
    image: postgres
    container_name: ps01

  app:
    build: .
    container_name: app01
    restart: always
    volumes:
      - .:/var/www/CultureAnalyzer
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: ng01
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/local-conf.d:/etc/nginx/conf.d
      - ./static:/var/www/CultureAnalyzer/static
      - ./media:/var/www/CultureAnalyzer/media
    depends_on:
      - app
