# Generated by Django 2.1.5 on 2019-01-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('feedbacks', '0002_auto_20190129_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('feedback',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='feedback_has_recommendation',
                                   to='feedbacks.Feedback')),
            ],
        ),
    ]
