# Generated by Django 2.1.5 on 2019-01-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('feedbacks', '0003_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='feedbacks.Feedback'),
        ),
    ]
