# Generated by Django 2.1.5 on 2019-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20190206_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='indicator',
            field=models.CharField(choices=[('PDI', 'PDI'), ('IDV', 'IDV'), ('MAS', 'MAS'), ('UAI', 'UAI'), ('LTO', 'LTO'), ('IVR', 'IVR')], default='PDI', max_length=3),
        ),
    ]
