# Generated by Django 2.1.5 on 2019-03-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20190221_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Feedback'),
        ),
    ]
