# Generated by Django 2.1.5 on 2019-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0002_auto_20190130_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='type_of_quiz',
            field=models.CharField(choices=[(1, 'Business'), (2, 'General')],
                                   max_length=20),
        ),
    ]
