# Generated by Django 2.1.5 on 2019-02-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190130_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='numbers_of_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='type_of_quiz',
            field=models.CharField(choices=[('Business', 'Business'), ('General', 'General')], max_length=20),
        ),
    ]
