# Generated by Django 2.1.5 on 2019-02-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190206_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='numbers_of_questions',
        ),
    ]
