# Generated by Django 2.1.5 on 2019-02-07 21:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizzes_numbers_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
