# Generated by Django 2.1.5 on 2019-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190207_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='result',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
