# Generated by Django 2.1.5 on 2019-02-14 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190212_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
