# Generated by Django 2.1.5 on 2019-02-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190213_1557'),
        ('quiz', '0008_auto_20190214_1236'),
    ]

    operations = [
    ]
