# Generated by Django 2.1.5 on 2019-02-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190214_1233'),
        ('quiz', '0008_auto_20190214_1235'),
        ('quiz', '0010_auto_20190214_1352'),
    ]

    operations = [
    ]
