# Generated by Django 2.1.5 on 2019-01-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIndicator',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('PDI', models.PositiveIntegerField()),
                ('IND', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('MAS', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('UAI', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('LTO', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('IVR', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'countries_indicators',
                'ordering': ['iso_code', 'name'],
            },
        ),
    ]
