# Generated by Django 2.1.5 on 2019-01-20 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIndicator',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('PDI', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('IND', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('MAS', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('UAI', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('LTO', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('IVR', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'countries_indicators',
            },
        ),
    ]
