# Generated by Django 2.1.5 on 2019-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIndicator',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('PDI', models.SmallIntegerField()),
                ('IND', models.SmallIntegerField()),
                ('MAS', models.SmallIntegerField()),
                ('UAI', models.SmallIntegerField()),
                ('LTO', models.SmallIntegerField()),
                ('IVR', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'CountriesIndicators',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'Feedbacks',
            },
        ),
    ]
