# Generated by Django 2.1.5 on 2019-02-13 13:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20190201_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryindicator',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z]{3}$', 2))]),
        ),
    ]
