# Generated by Django 2.1.5 on 2019-02-05 16:04

import re
import django.core.validators
from django.db import migrations, models

import indicators.models


class Migration(migrations.Migration):
    dependencies = [
        ('indicators', '0004_auto_20190201_1435'),
        ]

    operations = [
        migrations.AlterField(
            model_name='countryindicator',
            name='ind',
            field=indicators.models.IndicatorField(verbose_name='IND'),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True, validators=[
                django.core.validators.RegexValidator(
                    re.compile('^[a-z]{3}$', 2))]),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='ivr',
            field=indicators.models.IndicatorField(verbose_name='IVR'),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='lto',
            field=indicators.models.IndicatorField(verbose_name='LTO'),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='mas',
            field=indicators.models.IndicatorField(verbose_name='MAS'),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='pdi',
            field=indicators.models.IndicatorField(verbose_name='PDI'),
            ),
        migrations.AlterField(
            model_name='countryindicator',
            name='uai',
            field=indicators.models.IndicatorField(verbose_name='UAI'),
            ),
        ]
