# Generated by Django 2.1.5 on 2019-03-18 11:14

from django.db import migrations

from indicators.models import IndicatorField


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20190314_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryindicator',
            old_name='ind',
            new_name='idv',
        ),
        migrations.AlterField(
            model_name='countryindicator',
            name='idv',
            field=IndicatorField(verbose_name='IDV'),
            ),
    ]
