# Generated by Django 2.1.5 on 2019-02-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20190219_2012'),
        ('indicators', '0005_auto_20190219_2231'),
    ]

    operations = [
    ]
