# Generated by Django 2.1.5 on 2019-02-04 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0004_auto_20190124_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mentor',
                 models.ManyToManyField(related_name='mentor_in_group',
                                        to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='user_in_group',
                                                to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
