# Generated by Django 2.1.5 on 2019-01-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190129_2133'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ManyToManyField(related_name='mentor_in_group', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(related_name='user_in_group', to='users.Profile'),
        ),
    ]
