# Generated by Django 2.1.5 on 2019-02-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190210_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
