# Generated by Django 2.1.5 on 2019-03-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_dateofquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_mentor_group', 'Can view mentor group'), ('change_mentor_group', 'Can change mentor group'), ('create_mentor_group', 'Can create mentor group'), ('delete_mentor_group', 'Can delete mentor group'))},
        ),
    ]
