# Generated by Django 2.1.5 on 2019-03-19 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('groups', '0002_auto_20190314_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('items_left', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'permissions':
                         (('view_mentor_group', 'Can view mentor group'),
                          ('change_mentor_group', 'Can change mentor group'),
                          ('add_mentor_group', 'Can add mentor to group'))},
        ),
        migrations.AlterField(
            model_name='group',
            name='mentor',
            field=models.ManyToManyField(blank=True,
                                         related_name='mentor_in_group',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(blank=True,
                                         related_name='user_in_group',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shedule',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='groups.Group'),
        ),
        migrations.AddField(
            model_name='shedule',
            name='quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='quiz.Quizzes'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='groups.Group'),
        ),
    ]
