# Generated by Django 2.1.5 on 2019-01-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
