# Generated by Django 2.1.5 on 2019-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190129_1852'),
        ('groups', '0003_remove_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ManyToManyField(related_name='mentor_in_group', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(related_name='user_in_group', to='users.Profile'),
        ),
    ]
