# Generated by Django 2.1.5 on 2019-03-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190305_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_mentor_group', 'Can view mentor group'), ('change_mentor_group', 'Can change mentor group'), ('add_mentor_group', 'Can add mentor to group'))},
        ),
    ]
