# Generated by Django 2.1.5 on 2019-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190129_1852'),
        ('groups', '0004_auto_20190204_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.profile',),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
